documentation:
  - changed-files:
      - any-glob-to-any-file: .github/*
      - any-glob-to-any-file: CHANGELOG.md
      - any-glob-to-any-file: LICENSE
      - any-glob-to-any-file: README.md

test:
  - changed-files:
      - any-glob-to-any-file: test/*

example:
  - changed-files:
      - any-glob-to-any-file: example/*

  - changed-files:
      - any-glob-to-any-file: android/*

workflows:
  - changed-files:
      - any-glob-to-any-file: .github/workflows/*

lib:
  - changed-files:
      - any-glob-to-any-file: lib/*

