name: sunmi_scanner
description: "Sunmi support package that allows you to easily interface with your scanner device"
version: 0.0.5
repository: "https://github.com/FrenkyDema/sunmi_scanner"

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sunmi_scanner
        pluginClass: SunmiScannerPlugin
